version: '3'
services:
  webservice:
    restart: always
    ports:
      - 3000:3000
    build:
        context: ./app
    volumes:
      - ./app/bin:/app/bin
      - ./app/lib:/app/lib
networks:
  default:
    external:
      name: OOSE_Network