name: OOSE
description: A web server built using the shelf package.

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  args: ^1.4.2
  shelf: ^0.7.2
  sqljocky5: ^2.2.0

dev_dependencies:
  test: ^1.5.2
